### ISSUE TITLE
Command /createworld allows evil.

### ISSUE THREAD

**Issue by rdebath** [fucksophie/Cla55ic#2]
if you `/createworld my/test` bad things happen.
But `/createworld ../../../../../tmp/world` actually works ...

**Comment by fucksophie** [comment]
UHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by fucksophie** [comment]
this never happened

**Comment by MESYETI** [comment]
it happened!!
